name: Update PDF List

on:
  push:
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install pdfinfo
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils

      - name: Extract PDF Metadata and Sort by Date
        run: |
          echo "Generating index.html"
          PDF_LIST=""
          for pdf in *.pdf; do
            BASENAME=$(basename "$pdf")
            PDF_METADATA=$(pdfinfo "$pdf")
            PDF_NAME=$(echo "$PDF_METADATA" | grep -i "Title:" | awk -F': ' '{print $2}' | sed 's/^\s*//g' | tr -d '\n')
            PDF_DATE=$(echo "$PDF_METADATA" | grep -i "CreationDate:" | awk -F': ' '{print $2}' | sed 's/^\s*//g' | tr -d '\n')
            if [ -z "$PDF_NAME" ]; then
              PDF_NAME=$BASENAME
            fi
            if [ -z "$PDF_DATE" ]; then
              PDF_DATE="Unknown Date"
            fi
            PDF_LIST="$PDF_LIST<$pdf|$PDF_DATE>,"
          done

          if [ -z "$PDF_LIST" ]; then
            PDF_LIST="<li>No PDFs available</li>"
          else
            PDF_LIST=$(echo "$PDF_LIST" | tr ',' '\n' | sort -k2 | tr '\n' '<br>')
          fi

          cat <<EOF > index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>PDF List</title>
              <style>
                  body { font-family: Arial, sans-serif; margin: 20px; }
                  h1 { text-align: center; }
                  ul { list-style-type: none; padding: 0; }
                  li { margin: 10px 0; }
                  a { text-decoration: none; color: #007BFF; }
                  a:hover { text-decoration: underline; }
              </style>
          </head>
          <body>
              <h1>Available PDFs</h1>
              <ul id="pdf-list">
                  $PDF_LIST
              </ul>
          </body>
          </html>
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'index.html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

